param([string]$HostName=$(if($env:JIMCLAW_EXTERNAL_EXECUTOR_HOST){$env:JIMCLAW_EXTERNAL_EXECUTOR_HOST}else{'127.0.0.1'}),[int]$Port=$(if($env:JIMCLAW_EXTERNAL_EXECUTOR_PORT){[int]$env:JIMCLAW_EXTERNAL_EXECUTOR_PORT}else{4318}),[string]$Token=$(if($env:JIMCLAW_EXTERNAL_EXECUTOR_TOKEN){$env:JIMCLAW_EXTERNAL_EXECUTOR_TOKEN}else{''}))
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Send-Json($s,[int]$code,$obj){$txt=$obj|ConvertTo-Json -Depth 8 -Compress;$body=[Text.Encoding]::UTF8.GetBytes($txt);$status=@{200='OK';400='Bad Request';401='Unauthorized';404='Not Found'}[$code];if(-not $status){$status='Internal Server Error'};$head=[Text.Encoding]::ASCII.GetBytes("HTTP/1.1 $code $status`r`nContent-Type: application/json; charset=utf-8`r`nContent-Length: $($body.Length)`r`nConnection: close`r`n`r`n");$s.Write($head,0,$head.Length);$s.Write($body,0,$body.Length);$s.Flush()}
function Read-Req($c){$s=$c.GetStream();$r=[IO.StreamReader]::new($s,[Text.Encoding]::UTF8,$false,4096,$true);$first=$r.ReadLine();if([string]::IsNullOrWhiteSpace($first)){return @{stream=$s;method='';path='';headers=@{};body=''}};$parts=$first.Split(' ');$h=@{};while($true){$line=$r.ReadLine();if($null -eq $line -or $line -eq ''){break};$i=$line.IndexOf(':');if($i -gt 0){$h[$line.Substring(0,$i).Trim()]=$line.Substring($i+1).Trim()}};$len=0;if($h.ContainsKey('Content-Length')){[void][int]::TryParse([string]$h['Content-Length'],[ref]$len)};$body='';if($len -gt 0){$buf=New-Object char[] $len;$off=0;while($off -lt $len){$read=$r.Read($buf,$off,$len-$off);if($read -le 0){break};$off+=$read};if($off -gt 0){$body=-join $buf[0..($off-1)]}};@{stream=$s;method=if($parts.Length-ge 1){$parts[0]}else{''};path=if($parts.Length-ge 2){$parts[1]}else{''};headers=$h;body=$body}}
function Classify([string]$t){if($t -match 'spawn EPERM|EACCES|Access is denied'){return 'process_spawn_denied'};if($t -match 'ENOENT|is not recognized'){return 'command_not_found'};if($t -match 'timeout|timed out'){return 'timeout'};if($t -match 'EADDRINUSE|port already in use'){return 'port_conflict'};'executor_unavailable'}
function Paths([string]$w){$d=Join-Path $w '.jimclaw';@{dir=$d;pid=(Join-Path $d 'server.pid');out=(Join-Path $d 'server.stdout.log');err=(Join-Path $d 'server.stderr.log')}}
function Run-Intent($intent){if(($intent.PSObject.Properties.Name -contains 'background') -and $intent.background){$p=Paths $intent.workspace;New-Item -ItemType Directory -Force -Path $p.dir|Out-Null;if(Test-Path $p.pid){$old=Get-Content $p.pid -ErrorAction SilentlyContinue;if($old){Stop-Process -Id $old -Force -ErrorAction SilentlyContinue}};try{$proc=Start-Process -FilePath 'cmd.exe' -ArgumentList '/d','/s','/c',$intent.command -WorkingDirectory $intent.workspace -RedirectStandardOutput $p.out -RedirectStandardError $p.err -PassThru;Set-Content -Path $p.pid -Value $proc.Id;return @{ok=$true;backend='external_executor';stdout=[string]$proc.Id;stderr='';retryable=$false;requiresApproval=$false;blocked=$false;artifacts=@{pidPath=$p.pid;stdoutLogPath=$p.out;stderrLogPath=$p.err}}}catch{$m=$_.Exception.Message;return @{ok=$false;backend='external_executor';stdout='';stderr=$m;retryable=$false;requiresApproval=$false;blocked=$true;blockedReason=$m;failureType=(Classify $m)}}};$psi=[Diagnostics.ProcessStartInfo]::new();$psi.FileName='cmd.exe';$psi.Arguments="/d /s /c `"$($intent.command)`"";$psi.WorkingDirectory=$intent.workspace;$psi.UseShellExecute=$false;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$proc=[Diagnostics.Process]::new();$proc.StartInfo=$psi;try{[void]$proc.Start();$o=$proc.StandardOutput.ReadToEnd();$e=$proc.StandardError.ReadToEnd();$proc.WaitForExit();@{ok=($proc.ExitCode-eq 0);backend='external_executor';stdout=$o;stderr=$e;exitCode=$proc.ExitCode;retryable=$false;requiresApproval=$false;blocked=$false;failureType=$(if($proc.ExitCode-eq 0){$null}else{Classify "$e`n$o"})}}catch{$m=$_.Exception.Message;@{ok=$false;backend='external_executor';stdout='';stderr=$m;retryable=$false;requiresApproval=$false;blocked=$true;blockedReason=$m;failureType=(Classify $m)}}finally{$proc.Dispose()}}
$listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Parse($HostName),$Port);$listener.Start();Write-Host "[执行器 Sidecar] 已监听 http://${HostName}:${Port}"
try{while($true){$client=$listener.AcceptTcpClient();$req=$null;try{$req=Read-Req $client;$stream=[Net.Sockets.NetworkStream]$req.stream;if($req.method -eq 'GET' -and $req.path -eq '/capabilities'){Send-Json $stream 200 @{available=$true;name='jimclaw-executor-sidecar-powershell';backgroundProcess=@{available=$true};shell=@{available=$true};platform='win32-powershell';pid=$PID};continue};if($req.method -eq 'POST' -and $req.path -eq '/execute'){$auth=if($req.headers.ContainsKey('Authorization')){[string]$req.headers['Authorization']}else{''};if($Token -and $auth -ne "Bearer $Token"){Send-Json $stream 401 @{ok=$false;backend='external_executor';stdout='';stderr='unauthorized';retryable=$false;requiresApproval=$false;blocked=$true;blockedReason='unauthorized';failureType='permission_required'};continue};$body=if([string]::IsNullOrWhiteSpace([string]$req.body)){$null}else{([string]$req.body|ConvertFrom-Json)};if(-not $body -or -not $body.intent -or -not $body.intent.workspace -or -not $body.intent.kind){Send-Json $stream 400 @{ok=$false;backend='external_executor';stdout='';stderr='invalid intent payload';retryable=$false;requiresApproval=$false;blocked=$true;blockedReason='invalid intent payload';failureType='executor_unavailable'};continue};Send-Json $stream 200 (Run-Intent $body.intent);continue};Send-Json $stream 404 @{ok=$false;error='not_found'}}catch{try{if($req -and $req.stream){Send-Json ([Net.Sockets.NetworkStream]$req.stream) 500 @{ok=$false;backend='external_executor';stdout='';stderr=$_.Exception.Message;retryable=$false;requiresApproval=$false;blocked=$true;blockedReason=$_.Exception.Message;failureType=(Classify $_.Exception.Message)}}}catch{}}finally{$client.Close()}}}finally{$listener.Stop()}


